import{aggregateConfidence}from"../confidence.js";import{angleDegrees}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";import type{BodySide}from"./pilates-shoulder-bridge.js";
export interface PilatesPlankOptions{side?:BodySide;maximumAlignmentDeviationDegrees?:number;minimumHoldDurationMs?:number}
const DISCLAIMER="Estimativa 2D do Pilates Plank para pesquisa e apoio à decisão. Não mede força, ativação muscular, fadiga fisiológica ou carga lombar; requer vista lateral, confirmação profissional e não constitui diagnóstico.";
export function runPilatesPlankProtocol(frames:readonly PoseFrame[],options:PilatesPlankOptions={},now=new Date()):EngineResult{
 const side=options.side??"left",i=side==="left"?{shoulder:11,elbow:13,wrist:15,hip:23,ankle:27}:{shoulder:12,elbow:14,wrist:16,hip:24,ankle:28},quality=assessQuality(frames,{requiredLandmarkIndexes:Object.values(i),minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:10});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=first.landmarks[i.shoulder]!,h0=first.landmarks[i.hip]!,torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const samples=frames.flatMap(frame=>{const shoulder=frame.landmarks[i.shoulder],elbow=frame.landmarks[i.elbow],wrist=frame.landmarks[i.wrist],hip=frame.landmarks[i.hip],ankle=frame.landmarks[i.ankle];if(!shoulder||!elbow||!wrist||!hip||!ankle)return[];const alignment=angleDegrees(shoulder,hip,ankle),elbowAngle=angleDegrees(shoulder,elbow,wrist);if(alignment===null||elbowAngle===null)return[];return[{timestampMs:frame.timestampMs,alignmentDeviation:Math.abs(180-alignment),elbowAngle,pelvicDrift:Math.hypot(hip.x-h0.x,hip.y-h0.y)/torso,trunkSway:Math.hypot((shoulder.x-hip.x)-(s0.x-h0.x),(shoulder.y-hip.y)-(s0.y-h0.y))/torso}]});
 const maximum=options.maximumAlignmentDeviationDegrees??20,minimumDuration=options.minimumHoldDurationMs??1500;let start=-1,bestStart=-1,bestEnd=-1;for(let n=0;n<samples.length;n++){if(samples[n]!.alignmentDeviation<=maximum){if(start<0)start=n;if(bestStart<0||samples[n]!.timestampMs-samples[start]!.timestampMs>samples[bestEnd]!.timestampMs-samples[bestStart]!.timestampMs){bestStart=start;bestEnd=n}}else start=-1}
 const holdDuration=bestStart>=0?(samples[bestEnd]!.timestampMs-samples[bestStart]!.timestampMs)/1000:0;if(holdDuration*1000<minimumDuration){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Sustentação alinhada insuficiente para caracterizar a prancha.",details:{holdDurationSeconds:holdDuration,minimumHoldDurationSeconds:minimumDuration/1000}});return result([],quality,0,now)}
 const valid=samples.slice(bestStart,bestEnd+1),confidence=aggregateConfidence(quality,valid.length/frames.length),range=(key:"alignmentDeviation"|"elbowAngle")=>Math.max(...valid.map(s=>s[key]))-Math.min(...valid.map(s=>s[key]));
 return result([metric("plank_valid_hold_duration",holdDuration,"s",confidence),metric("plank_valid_frame_ratio",valid.length/samples.length,"ratio",confidence),metric("plank_alignment_deviation_mean",mean(valid.map(s=>s.alignmentDeviation)),"deg",confidence),metric("plank_alignment_deviation_max",Math.max(...valid.map(s=>s.alignmentDeviation)),"deg",confidence),metric("plank_alignment_variation",range("alignmentDeviation"),"deg",confidence),metric("plank_pelvic_drift_max",Math.max(...valid.map(s=>s.pelvicDrift)),"torso_ratio",confidence),metric("plank_trunk_sway_max",Math.max(...valid.map(s=>s.trunkSway)),"torso_ratio",confidence),metric("plank_elbow_angle_range",range("elbowAngle"),"deg",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-plank",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
