import{aggregateConfidence}from"../confidence.js";import{midpoint}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";
export interface PilatesBirdDogOptions{minimumContralateralDifferenceRatio?:number;minimumStableFrames?:number;minimumAlternations?:number}
type BirdDogState="left_arm_right_leg"|"right_arm_left_leg"|"neutral";
const DISCLAIMER="Estimativa 2D do Bird Dog/Quadruped para pesquisa e apoio à decisão. Não mede controle neuromuscular profundo, carga lombar ou rotação tridimensional; requer vista lateral ou oblíqua, confirmação profissional e não constitui diagnóstico.";
export function runPilatesBirdDogProtocol(frames:readonly PoseFrame[],options:PilatesBirdDogOptions={},now=new Date()):EngineResult{
 const required=[11,12,15,16,23,24,27,28]as const,quality=assessQuality(frames,{requiredLandmarkIndexes:required,minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:12});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=midpoint(first.landmarks[11]!,first.landmarks[12]!),h0=midpoint(first.landmarks[23]!,first.landmarks[24]!),torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const b={lw:first.landmarks[15]!.x,rw:first.landmarks[16]!.x,la:first.landmarks[27]!.x,ra:first.landmarks[28]!.x},threshold=options.minimumContralateralDifferenceRatio??.18;
 const samples=frames.map(frame=>{const shoulder=midpoint(frame.landmarks[11]!,frame.landmarks[12]!),hip=midpoint(frame.landmarks[23]!,frame.landmarks[24]!),leftArm=(b.lw-frame.landmarks[15]!.x)/torso,rightArm=(b.rw-frame.landmarks[16]!.x)/torso,leftLeg=(frame.landmarks[27]!.x-b.la)/torso,rightLeg=(frame.landmarks[28]!.x-b.ra)/torso,a=leftArm+rightLeg,c=rightArm+leftLeg,difference=a-c,state:BirdDogState=difference>=threshold?"left_arm_right_leg":difference<=-threshold?"right_arm_left_leg":"neutral";return{timestampMs:frame.timestampMs,state,leftArm,rightArm,leftLeg,rightLeg,diagonalImbalance:Math.abs(leftArm-rightLeg)+Math.abs(rightArm-leftLeg),pelvicDrift:Math.hypot(hip.x-h0.x,hip.y-h0.y)/torso,trunkDrift:Math.hypot((shoulder.x-hip.x)-(s0.x-h0.x),(shoulder.y-hip.y)-(s0.y-h0.y))/torso}});
 const stable=options.minimumStableFrames??2,states:Array<{state:Exclude<BirdDogState,"neutral">;timestampMs:number}>=[];let candidate:BirdDogState="neutral",run=0;for(const sample of samples){if(sample.state==="neutral"){candidate="neutral";run=0;continue}if(candidate===sample.state)run++;else{candidate=sample.state;run=1}if(run===stable&&states.at(-1)?.state!==candidate)states.push({state:candidate,timestampMs:sample.timestampMs})}
 const alternations=states.slice(1).filter((state,index)=>state.state!==states[index]!.state),minimum=options.minimumAlternations??2;if(alternations.length<minimum){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Alternância contralateral insuficiente para caracterizar o Bird Dog.",details:{alternations:alternations.length}});return result([],quality,0,now)}
 const duration=(states.at(-1)!.timestampMs-states[0]!.timestampMs)/1000,confidence=aggregateConfidence(quality,samples.length/frames.length),intervals=states.slice(1).map((state,index)=>(state.timestampMs-states[index]!.timestampMs)/1000),range=(key:"leftArm"|"rightArm"|"leftLeg"|"rightLeg")=>Math.max(...samples.map(s=>s[key]))-Math.min(...samples.map(s=>s[key]));
 return result([metric("bird_dog_alternation_count",alternations.length,"count",confidence),metric("bird_dog_cadence",duration>0?alternations.length/duration*60:0,"alternations_per_min",confidence),metric("bird_dog_switch_time",mean(intervals),"s",confidence),metric("bird_dog_left_arm_range",range("leftArm"),"torso_ratio",confidence),metric("bird_dog_right_arm_range",range("rightArm"),"torso_ratio",confidence),metric("bird_dog_left_leg_range",range("leftLeg"),"torso_ratio",confidence),metric("bird_dog_right_leg_range",range("rightLeg"),"torso_ratio",confidence),metric("bird_dog_diagonal_imbalance_mean",mean(samples.map(s=>s.diagonalImbalance)),"torso_ratio",confidence),metric("bird_dog_pelvic_drift_max",Math.max(...samples.map(s=>s.pelvicDrift)),"torso_ratio",confidence),metric("bird_dog_trunk_drift_max",Math.max(...samples.map(s=>s.trunkDrift)),"torso_ratio",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-bird-dog",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
