import{aggregateConfidence}from"../confidence.js";import{angleDegrees}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";import type{BodySide}from"./pilates-shoulder-bridge.js";
export interface PilatesTeaserOptions{side?:BodySide;minimumShoulderLiftRatio?:number;minimumLegLiftRatio?:number;returnToleranceRatio?:number;minimumRepetitionDurationMs?:number}
const DISCLAIMER="Estimativa 2D do Pilates Teaser para pesquisa e apoio à decisão. Não mede força abdominal, controle segmentar da coluna ou carga lombar; requer vista lateral, confirmação profissional e não constitui diagnóstico.";
export function runPilatesTeaserProtocol(frames:readonly PoseFrame[],options:PilatesTeaserOptions={},now=new Date()):EngineResult{
 const side=options.side??"left",i=side==="left"?{shoulder:11,hip:23,knee:25,ankle:27}:{shoulder:12,hip:24,knee:26,ankle:28},quality=assessQuality(frames,{requiredLandmarkIndexes:Object.values(i),minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:12});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=first.landmarks[i.shoulder]!,h0=first.landmarks[i.hip]!,a0=first.landmarks[i.ankle]!,torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const baselineTrunk=Math.atan2(s0.y-h0.y,s0.x-h0.x)*180/Math.PI,samples=frames.flatMap(frame=>{const shoulder=frame.landmarks[i.shoulder],hip=frame.landmarks[i.hip],knee=frame.landmarks[i.knee],ankle=frame.landmarks[i.ankle];if(!shoulder||!hip||!knee||!ankle)return[];const kneeAngle=angleDegrees(hip,knee,ankle),vAngle=angleDegrees(shoulder,hip,ankle);if(kneeAngle===null||vAngle===null)return[];const trunk=Math.atan2(shoulder.y-hip.y,shoulder.x-hip.x)*180/Math.PI;return[{timestampMs:frame.timestampMs,shoulderLift:(s0.y-shoulder.y)/torso,legLift:(a0.y-ankle.y)/torso,trunkFlexion:Math.abs(trunk-baselineTrunk),vAngle,kneeAngle,pelvicDrift:Math.hypot(hip.x-h0.x,hip.y-h0.y)/torso}]});
 const shoulderMinimum=options.minimumShoulderLiftRatio??.15,legMinimum=options.minimumLegLiftRatio??.12,tolerance=options.returnToleranceRatio??.05,minDuration=options.minimumRepetitionDurationMs??700,reps:Array<{start:number;end:number}>=[];let start=-1;samples.forEach((sample,index)=>{if(start<0&&sample.shoulderLift>=shoulderMinimum&&sample.legLift>=legMinimum)start=index;if(start>=0&&sample.shoulderLift<=tolerance&&sample.legLift<=tolerance){if(sample.timestampMs-samples[start]!.timestampMs>=minDuration)reps.push({start,end:index});start=-1}});
 if(!reps.length){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Nenhum ciclo completo e combinado de subida e retorno do Teaser foi detectado.",details:{maximumShoulderLiftRatio:Math.max(...samples.map(s=>s.shoulderLift)),maximumLegLiftRatio:Math.max(...samples.map(s=>s.legLift))}});return result([],quality,0,now)}
 const confidence=aggregateConfidence(quality,samples.length/frames.length),durations=reps.map(rep=>(samples[rep.end]!.timestampMs-samples[rep.start]!.timestampMs)/1000),synchronization=reps.map(rep=>{const segment=samples.slice(rep.start,rep.end+1),trunkPeak=segment.reduce((best,s,index)=>s.trunkFlexion>segment[best]!.trunkFlexion?index:best,0),legPeak=segment.reduce((best,s,index)=>s.legLift>segment[best]!.legLift?index:best,0);return Math.abs(segment[trunkPeak]!.timestampMs-segment[legPeak]!.timestampMs)/1000}),range=(key:"trunkFlexion"|"legLift"|"kneeAngle"|"vAngle")=>Math.max(...samples.map(s=>s[key]))-Math.min(...samples.map(s=>s[key]));
 return result([metric("repetition_count",reps.length,"count",confidence),metric("teaser_shoulder_lift_peak",Math.max(...samples.map(s=>s.shoulderLift)),"torso_ratio",confidence),metric("teaser_trunk_flexion_range",range("trunkFlexion"),"deg",confidence),metric("teaser_leg_lift_range",range("legLift"),"torso_ratio",confidence),metric("teaser_v_angle_min",Math.min(...samples.map(s=>s.vAngle)),"deg",confidence),metric("teaser_v_angle_range",range("vAngle"),"deg",confidence),metric("teaser_knee_angle_range",range("kneeAngle"),"deg",confidence),metric("teaser_peak_synchronization_error",mean(synchronization),"s",confidence),metric("teaser_pelvic_drift_max",Math.max(...samples.map(s=>s.pelvicDrift)),"torso_ratio",confidence),metric("repetition_time",mean(durations),"s",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-teaser",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
