import{aggregateConfidence}from"../confidence.js";import{angleDegrees}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";import type{BodySide}from"./pilates-shoulder-bridge.js";
export interface PilatesSideKickOptions{movingSide?:BodySide;minimumExcursionRatio?:number;minimumStableFrames?:number;minimumRepetitions?:number}
type KickState="front"|"back"|"neutral";
const DISCLAIMER="Estimativa 2D do Pilates Side Kick para pesquisa e apoio à decisão. Não mede rotação tridimensional do quadril nem carga articular; requer vista lateral adequada, confirmação profissional e não constitui diagnóstico.";
export function runPilatesSideKickProtocol(frames:readonly PoseFrame[],options:PilatesSideKickOptions={},now=new Date()):EngineResult{
 const side=options.movingSide??"left",i=side==="left"?{shoulder:11,hip:23,knee:25,ankle:27}:{shoulder:12,hip:24,knee:26,ankle:28},quality=assessQuality(frames,{requiredLandmarkIndexes:Object.values(i),minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:12});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=first.landmarks[i.shoulder]!,h0=first.landmarks[i.hip]!,a0=first.landmarks[i.ankle]!,torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const threshold=options.minimumExcursionRatio??.15,baseline=a0.x-h0.x,samples=frames.flatMap(frame=>{const shoulder=frame.landmarks[i.shoulder],hip=frame.landmarks[i.hip],knee=frame.landmarks[i.knee],ankle=frame.landmarks[i.ankle];if(!shoulder||!hip||!knee||!ankle)return[];const kneeAngle=angleDegrees(hip,knee,ankle);if(kneeAngle===null)return[];const excursion=((ankle.x-hip.x)-baseline)/torso,state:KickState=excursion>=threshold?"front":excursion<=-threshold?"back":"neutral";return[{timestampMs:frame.timestampMs,state,excursion,kneeAngle,pelvicDrift:Math.hypot(hip.x-h0.x,hip.y-h0.y)/torso,trunkDrift:Math.hypot((shoulder.x-hip.x)-(s0.x-h0.x),(shoulder.y-hip.y)-(s0.y-h0.y))/torso}]});
 const stable=options.minimumStableFrames??2,states:Array<{state:Exclude<KickState,"neutral">;timestampMs:number}>=[];let candidate:KickState="neutral",run=0;for(const sample of samples){if(sample.state==="neutral"){candidate="neutral";run=0;continue}if(candidate===sample.state)run++;else{candidate=sample.state;run=1}if(run===stable&&states.at(-1)?.state!==candidate)states.push({state:candidate,timestampMs:sample.timestampMs})}
 const transitions=states.slice(1).filter((state,index)=>state.state!==states[index]!.state),repetitions=Math.floor(transitions.length/2),minimum=options.minimumRepetitions??1;if(repetitions<minimum){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Nenhum ciclo completo frente–trás–frente do Side Kick foi detectado.",details:{transitions:transitions.length}});return result([],quality,0,now)}
 const confidence=aggregateConfidence(quality,samples.length/frames.length),intervals=states.slice(1).map((state,index)=>(state.timestampMs-states[index]!.timestampMs)/1000),range=(key:"excursion"|"kneeAngle")=>Math.max(...samples.map(s=>s[key]))-Math.min(...samples.map(s=>s[key]));
 return result([metric("repetition_count",repetitions,"count",confidence),metric("side_kick_excursion_range",range("excursion"),"torso_ratio",confidence),metric("side_kick_front_peak",Math.max(...samples.map(s=>s.excursion)),"torso_ratio",confidence),metric("side_kick_back_peak",Math.abs(Math.min(...samples.map(s=>s.excursion))),"torso_ratio",confidence),metric("side_kick_switch_time",mean(intervals),"s",confidence),metric("side_kick_knee_angle_range",range("kneeAngle"),"deg",confidence),metric("side_kick_pelvic_drift_max",Math.max(...samples.map(s=>s.pelvicDrift)),"torso_ratio",confidence),metric("side_kick_trunk_drift_max",Math.max(...samples.map(s=>s.trunkDrift)),"torso_ratio",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-side-kick",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
