import{aggregateConfidence}from"../confidence.js";import{midpoint}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";
export interface PilatesSawOptions{minimumReachDifference?:number;minimumStableFrames?:number;minimumAlternations?:number}
type SawState="left_to_right"|"right_to_left"|"neutral";
const DISCLAIMER="Estimativa 2D do Pilates Saw para pesquisa e apoio à decisão. Rotação axial e articulação segmentar da coluna não são medidas diretamente; requer confirmação profissional e não constitui diagnóstico.";
export function runPilatesSawProtocol(frames:readonly PoseFrame[],options:PilatesSawOptions={},now=new Date()):EngineResult{
 const required=[11,12,15,16,23,24,27,28]as const,quality=assessQuality(frames,{requiredLandmarkIndexes:required,minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:12});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=midpoint(first.landmarks[11]!,first.landmarks[12]!),h0=midpoint(first.landmarks[23]!,first.landmarks[24]!),torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const threshold=options.minimumReachDifference??.18,samples=frames.map(frame=>{const shoulder=midpoint(frame.landmarks[11]!,frame.landmarks[12]!),hip=midpoint(frame.landmarks[23]!,frame.landmarks[24]!),leftReach=Math.hypot(frame.landmarks[15]!.x-frame.landmarks[28]!.x,frame.landmarks[15]!.y-frame.landmarks[28]!.y)/torso,rightReach=Math.hypot(frame.landmarks[16]!.x-frame.landmarks[27]!.x,frame.landmarks[16]!.y-frame.landmarks[27]!.y)/torso,difference=rightReach-leftReach;const state:SawState=difference>=threshold?"left_to_right":difference<=-threshold?"right_to_left":"neutral";const shoulderTilt=Math.atan2(frame.landmarks[12]!.y-frame.landmarks[11]!.y,frame.landmarks[12]!.x-frame.landmarks[11]!.x)*180/Math.PI;return{timestampMs:frame.timestampMs,state,leftReach,rightReach,shoulderTilt,pelvicDrift:Math.hypot(hip.x-h0.x,hip.y-h0.y)/torso}});
 const stable=options.minimumStableFrames??2,states:Array<{state:Exclude<SawState,"neutral">;timestampMs:number}>=[];let candidate:SawState="neutral",run=0;for(const sample of samples){if(sample.state==="neutral"){candidate="neutral";run=0;continue}if(candidate===sample.state)run++;else{candidate=sample.state;run=1}if(run===stable&&states.at(-1)?.state!==candidate)states.push({state:candidate,timestampMs:sample.timestampMs})}
 const alternations=states.slice(1).filter((state,index)=>state.state!==states[index]!.state),minimum=options.minimumAlternations??2;if(alternations.length<minimum){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Alternância cruzada insuficiente para caracterizar o Saw.",details:{alternations:alternations.length,minimumAlternations:minimum}});return result([],quality,0,now)}
 const confidence=aggregateConfidence(quality,samples.length/frames.length),intervals=states.slice(1).map((state,index)=>(state.timestampMs-states[index]!.timestampMs)/1000),range=(key:"leftReach"|"rightReach"|"shoulderTilt")=>Math.max(...samples.map(s=>s[key]))-Math.min(...samples.map(s=>s[key]));
 return result([metric("saw_alternation_count",alternations.length,"count",confidence),metric("saw_switch_time",mean(intervals),"s",confidence),metric("saw_left_cross_reach_range",range("leftReach"),"torso_ratio",confidence),metric("saw_right_cross_reach_range",range("rightReach"),"torso_ratio",confidence),metric("saw_shoulder_rotation_proxy_range",range("shoulderTilt"),"deg",confidence),metric("saw_pelvic_drift_max",Math.max(...samples.map(s=>s.pelvicDrift)),"torso_ratio",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-saw",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
