import{aggregateConfidence}from"../confidence.js";import{angleDegrees,midpoint}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";
export interface PilatesLegPullFrontOptions{minimumLiftDifferenceRatio?:number;minimumStableFrames?:number;minimumAlternations?:number}
type LegState="left"|"right"|"neutral";
const DISCLAIMER="Estimativa 2D do Pilates Leg Pull Front para pesquisa e apoio à decisão. Não mede carga lombar, ativação muscular ou alinhamento tridimensional; requer vista lateral, confirmação profissional e não constitui diagnóstico.";
export function runPilatesLegPullFrontProtocol(frames:readonly PoseFrame[],options:PilatesLegPullFrontOptions={},now=new Date()):EngineResult{
 const required=[11,12,23,24,25,26,27,28]as const,quality=assessQuality(frames,{requiredLandmarkIndexes:required,minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:12});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=midpoint(first.landmarks[11]!,first.landmarks[12]!),h0=midpoint(first.landmarks[23]!,first.landmarks[24]!),torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const baselineLeft=first.landmarks[27]!.y,baselineRight=first.landmarks[28]!.y,threshold=options.minimumLiftDifferenceRatio??.12,samples=frames.flatMap(frame=>{const shoulder=midpoint(frame.landmarks[11]!,frame.landmarks[12]!),hip=midpoint(frame.landmarks[23]!,frame.landmarks[24]!),leftKnee=angleDegrees(frame.landmarks[23]!,frame.landmarks[25]!,frame.landmarks[27]!),rightKnee=angleDegrees(frame.landmarks[24]!,frame.landmarks[26]!,frame.landmarks[28]!);if(leftKnee===null||rightKnee===null)return[];const leftLift=(baselineLeft-frame.landmarks[27]!.y)/torso,rightLift=(baselineRight-frame.landmarks[28]!.y)/torso,difference=leftLift-rightLift,state:LegState=difference>=threshold?"left":difference<=-threshold?"right":"neutral";const supportAnkle=state==="left"?frame.landmarks[28]!:frame.landmarks[27]!,alignment=angleDegrees(shoulder,hip,supportAnkle);if(alignment===null)return[];return[{timestampMs:frame.timestampMs,state,leftLift,rightLift,leftKnee,rightKnee,alignmentDeviation:Math.abs(180-alignment),pelvicDrift:Math.hypot(hip.x-h0.x,hip.y-h0.y)/torso}]});
 const stable=options.minimumStableFrames??2,states:Array<{state:Exclude<LegState,"neutral">;timestampMs:number}>=[];let candidate:LegState="neutral",run=0;for(const sample of samples){if(sample.state==="neutral"){candidate="neutral";run=0;continue}if(candidate===sample.state)run++;else{candidate=sample.state;run=1}if(run===stable&&states.at(-1)?.state!==candidate)states.push({state:candidate,timestampMs:sample.timestampMs})}
 const alternations=states.slice(1).filter((state,index)=>state.state!==states[index]!.state),minimum=options.minimumAlternations??2;if(alternations.length<minimum){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Alternância de elevação das pernas insuficiente para caracterizar o Leg Pull Front.",details:{alternations:alternations.length}});return result([],quality,0,now)}
 const duration=(states.at(-1)!.timestampMs-states[0]!.timestampMs)/1000,confidence=aggregateConfidence(quality,samples.length/frames.length),intervals=states.slice(1).map((state,index)=>(state.timestampMs-states[index]!.timestampMs)/1000),range=(key:"leftLift"|"rightLift"|"leftKnee"|"rightKnee")=>Math.max(...samples.map(s=>s[key]))-Math.min(...samples.map(s=>s[key]));
 return result([metric("leg_pull_front_alternation_count",alternations.length,"count",confidence),metric("leg_pull_front_cadence",duration>0?alternations.length/duration*60:0,"alternations_per_min",confidence),metric("leg_pull_front_switch_time",mean(intervals),"s",confidence),metric("leg_pull_front_left_lift_range",range("leftLift"),"torso_ratio",confidence),metric("leg_pull_front_right_lift_range",range("rightLift"),"torso_ratio",confidence),metric("leg_pull_front_left_knee_range",range("leftKnee"),"deg",confidence),metric("leg_pull_front_right_knee_range",range("rightKnee"),"deg",confidence),metric("leg_pull_front_alignment_deviation_max",Math.max(...samples.map(s=>s.alignmentDeviation)),"deg",confidence),metric("leg_pull_front_pelvic_drift_max",Math.max(...samples.map(s=>s.pelvicDrift)),"torso_ratio",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-leg-pull-front",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
