import{aggregateConfidence}from"../confidence.js";import{angleDegrees,midpoint}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";import type{BodySide}from"./pilates-shoulder-bridge.js";
export interface PilatesSingleLegCircleOptions{movingSide?:BodySide;minimumRadiusRatio?:number;minimumCycles?:number}
const DISCLAIMER="Estimativa 2D do Pilates Single Leg Circle para pesquisa e apoio à decisão. A trajetória projetada não representa mobilidade tridimensional real do quadril; requer confirmação profissional e não constitui diagnóstico.";
export function runPilatesSingleLegCircleProtocol(frames:readonly PoseFrame[],options:PilatesSingleLegCircleOptions={},now=new Date()):EngineResult{
 const side=options.movingSide??"left",i=side==="left"?{knee:25,ankle:27}:{knee:26,ankle:28},required=[11,12,23,24,i.knee,i.ankle]as const,quality=assessQuality(frames,{requiredLandmarkIndexes:required,minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:16});if(!quality.accepted)return result([],quality,0,now);
 const firstHip=midpoint(frames[0]!.landmarks[23]!,frames[0]!.landmarks[24]!),shoulder=midpoint(frames[0]!.landmarks[11]!,frames[0]!.landmarks[12]!),torso=Math.hypot(shoulder.x-firstHip.x,shoulder.y-firstHip.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const samples=frames.flatMap(frame=>{const hip=midpoint(frame.landmarks[23]!,frame.landmarks[24]!),knee=frame.landmarks[i.knee],ankle=frame.landmarks[i.ankle];if(!knee||!ankle)return[];const kneeAngle=angleDegrees(hip,knee,ankle);if(kneeAngle===null)return[];const x=(ankle.x-hip.x)/torso,y=(ankle.y-hip.y)/torso;return[{timestampMs:frame.timestampMs,x,y,radius:Math.hypot(x,y),phase:Math.atan2(y,x),kneeAngle,pelvicDrift:Math.hypot(hip.x-firstHip.x,hip.y-firstHip.y)/torso}]});
 const minimumRadius=options.minimumRadiusRatio??.12,active=samples.filter(s=>s.radius>=minimumRadius);if(active.length<12){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Trajetória circular válida insuficiente.",details:{validFrames:active.length,minimumRadiusRatio:minimumRadius}});return result([],quality,0,now)}
 let cumulative=0;const cycleTimes:number[]=[];let nextCycle=2*Math.PI,lastCycleTime=active[0]!.timestampMs;for(let n=1;n<active.length;n++){let delta=active[n]!.phase-active[n-1]!.phase;if(delta>Math.PI)delta-=2*Math.PI;if(delta< -Math.PI)delta+=2*Math.PI;cumulative+=delta;while(Math.abs(cumulative)>=nextCycle){cycleTimes.push((active[n]!.timestampMs-lastCycleTime)/1000);lastCycleTime=active[n]!.timestampMs;nextCycle+=2*Math.PI}}
 const cycles=cycleTimes.length,minimumCycles=options.minimumCycles??1;if(cycles<minimumCycles){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Nenhum círculo completo foi detectado.",details:{angularTravelDegrees:Math.abs(cumulative)*180/Math.PI}});return result([],quality,0,now)}
 const confidence=aggregateConfidence(quality,active.length/frames.length),range=(key:"x"|"y"|"radius"|"kneeAngle")=>Math.max(...active.map(s=>s[key]))-Math.min(...active.map(s=>s[key]));
 return result([metric("single_leg_circle_count",cycles,"count",confidence),metric("single_leg_circle_cycle_time",mean(cycleTimes),"s",confidence),metric("single_leg_circle_horizontal_range",range("x"),"torso_ratio",confidence),metric("single_leg_circle_vertical_range",range("y"),"torso_ratio",confidence),metric("single_leg_circle_radius_variation",range("radius"),"torso_ratio",confidence),metric("single_leg_circle_knee_angle_range",range("kneeAngle"),"deg",confidence),metric("single_leg_circle_pelvic_drift_max",Math.max(...active.map(s=>s.pelvicDrift)),"torso_ratio",confidence),metric("single_leg_circle_direction",cumulative>=0?1:-1,"signed",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-single-leg-circle",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
