import{aggregateConfidence}from"../confidence.js";import{angleDegrees}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";import type{BodySide}from"./pilates-shoulder-bridge.js";
export interface PilatesRollDownOptions{side?:BodySide;minimumTrunkFlexionDegrees?:number;returnToleranceDegrees?:number;minimumRepetitionDurationMs?:number}
const DISCLAIMER="Estimativa 2D do Pilates Roll Down para pesquisa e apoio à decisão. Não mede articulação segmentar da coluna, requer confirmação profissional e não constitui diagnóstico.";
export function runPilatesRollDownProtocol(frames:readonly PoseFrame[],options:PilatesRollDownOptions={},now=new Date()):EngineResult{
 const side=options.side??"left",i=side==="left"?{ear:7,shoulder:11,hip:23,knee:25,ankle:27}:{ear:8,shoulder:12,hip:24,knee:26,ankle:28};
 const quality=assessQuality(frames,{requiredLandmarkIndexes:Object.values(i),minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:10});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=first.landmarks[i.shoulder]!,h0=first.landmarks[i.hip]!,torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);
 if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const samples=frames.flatMap((frame)=>{const ear=frame.landmarks[i.ear],shoulder=frame.landmarks[i.shoulder],hip=frame.landmarks[i.hip],knee=frame.landmarks[i.knee],ankle=frame.landmarks[i.ankle];if(!ear||!shoulder||!hip||!knee||!ankle)return[];const dx=shoulder.x-hip.x,dy=Math.abs(shoulder.y-hip.y),kneeAngle=angleDegrees(hip,knee,ankle),headAngle=angleDegrees(ear,shoulder,hip);if(kneeAngle===null||headAngle===null||(dx===0&&dy===0))return[];return[{timestampMs:frame.timestampMs,trunkFlexion:Math.atan2(Math.abs(dx),dy)*180/Math.PI,shoulderDescent:(shoulder.y-s0.y)/torso,kneeAngle,headTrunkAngle:headAngle}]});
 const minimum=options.minimumTrunkFlexionDegrees??20,tolerance=options.returnToleranceDegrees??8,minDuration=options.minimumRepetitionDurationMs??700;const reps:Array<{start:number;end:number}>=[];let start=-1;
 samples.forEach((sample,index)=>{if(start<0&&sample.trunkFlexion>=minimum)start=index;if(start>=0&&sample.trunkFlexion<=tolerance){if(sample.timestampMs-samples[start]!.timestampMs>=minDuration)reps.push({start,end:index});start=-1}});
 if(!reps.length){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Nenhum ciclo completo de flexão e retorno foi detectado.",details:{maximumTrunkFlexionDegrees:Math.max(...samples.map((sample)=>sample.trunkFlexion)),minimumTrunkFlexionDegrees:minimum}});return result([],quality,0,now)}
 const confidence=aggregateConfidence(quality,samples.length/frames.length),durations=reps.map((rep)=>(samples[rep.end]!.timestampMs-samples[rep.start]!.timestampMs)/1000);
 const range=(key:"trunkFlexion"|"kneeAngle"|"headTrunkAngle")=>Math.max(...samples.map((sample)=>sample[key]))-Math.min(...samples.map((sample)=>sample[key]));
 return result([metric("repetition_count",reps.length,"count",confidence),metric("roll_down_trunk_flexion_peak",Math.max(...samples.map((sample)=>sample.trunkFlexion)),"deg",confidence),metric("roll_down_trunk_flexion_range",range("trunkFlexion"),"deg",confidence),metric("roll_down_shoulder_descent_max",Math.max(...samples.map((sample)=>sample.shoulderDescent)),"torso_ratio",confidence),metric("roll_down_knee_angle_range",range("kneeAngle"),"deg",confidence),metric("roll_down_head_trunk_angle_range",range("headTrunkAngle"),"deg",confidence),metric("repetition_time",mean(durations),"s",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-roll-down",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
