import{aggregateConfidence}from"../confidence.js";import{angleDegrees}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";import type{BodySide}from"./pilates-shoulder-bridge.js";
export interface PilatesSwanOptions{side?:BodySide;minimumLiftRatio?:number;returnToleranceRatio?:number;minimumRepetitionDurationMs?:number}
const DISCLAIMER="Estimativa 2D do Pilates Swan para pesquisa e apoio à decisão. Não mede extensão segmentar da coluna nem carga lombar, requer vista lateral e confirmação profissional; não constitui diagnóstico.";
export function runPilatesSwanProtocol(frames:readonly PoseFrame[],options:PilatesSwanOptions={},now=new Date()):EngineResult{
 const side=options.side??"left",i=side==="left"?{shoulder:11,elbow:13,wrist:15,hip:23,knee:25}:{shoulder:12,elbow:14,wrist:16,hip:24,knee:26};
 const quality=assessQuality(frames,{requiredLandmarkIndexes:Object.values(i),minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:10});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=first.landmarks[i.shoulder]!,h0=first.landmarks[i.hip]!,torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);
 if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const baselineHipY=h0.y,baselineTrunkAngle=Math.atan2(s0.y-h0.y,s0.x-h0.x)*180/Math.PI;
 const samples=frames.flatMap((frame)=>{const shoulder=frame.landmarks[i.shoulder],elbow=frame.landmarks[i.elbow],wrist=frame.landmarks[i.wrist],hip=frame.landmarks[i.hip],knee=frame.landmarks[i.knee];if(!shoulder||!elbow||!wrist||!hip||!knee)return[];const elbowAngle=angleDegrees(shoulder,elbow,wrist);if(elbowAngle===null)return[];const trunkAngle=Math.atan2(shoulder.y-hip.y,shoulder.x-hip.x)*180/Math.PI;return[{timestampMs:frame.timestampMs,lift:(s0.y-shoulder.y)/torso,trunkExtension:Math.abs(trunkAngle-baselineTrunkAngle),elbowAngle,pelvicDrift:Math.abs(hip.y-baselineHipY)/torso}]});
 const minimum=options.minimumLiftRatio??.12,tolerance=options.returnToleranceRatio??.04,minDuration=options.minimumRepetitionDurationMs??500;const reps:Array<{start:number;end:number}>=[];let start=-1;
 samples.forEach((sample,index)=>{if(start<0&&sample.lift>=minimum)start=index;if(start>=0&&sample.lift<=tolerance){if(sample.timestampMs-samples[start]!.timestampMs>=minDuration)reps.push({start,end:index});start=-1}});
 if(!reps.length){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Nenhum ciclo completo de elevação e retorno do Swan foi detectado.",details:{maximumLiftRatio:Math.max(...samples.map((sample)=>sample.lift)),minimumLiftRatio:minimum}});return result([],quality,0,now)}
 const confidence=aggregateConfidence(quality,samples.length/frames.length),durations=reps.map((rep)=>(samples[rep.end]!.timestampMs-samples[rep.start]!.timestampMs)/1000),range=(key:"trunkExtension"|"elbowAngle")=>Math.max(...samples.map((sample)=>sample[key]))-Math.min(...samples.map((sample)=>sample[key]));
 return result([metric("repetition_count",reps.length,"count",confidence),metric("swan_upper_body_lift_peak",Math.max(...samples.map((sample)=>sample.lift)),"torso_ratio",confidence),metric("swan_trunk_extension_apparent_peak",Math.max(...samples.map((sample)=>sample.trunkExtension)),"deg",confidence),metric("swan_trunk_extension_apparent_range",range("trunkExtension"),"deg",confidence),metric("swan_elbow_angle_range",range("elbowAngle"),"deg",confidence),metric("swan_pelvic_drift_max",Math.max(...samples.map((sample)=>sample.pelvicDrift)),"torso_ratio",confidence),metric("repetition_time",mean(durations),"s",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-swan",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
