import{aggregateConfidence}from"../confidence.js";import{angleDegrees}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";import type{BodySide}from"./pilates-shoulder-bridge.js";
export interface PilatesSpineStretchForwardOptions{side?:BodySide;minimumFlexionDegrees?:number;returnToleranceDegrees?:number;minimumRepetitionDurationMs?:number}
const DISCLAIMER="Estimativa 2D do Pilates Spine Stretch Forward para pesquisa e apoio à decisão. Não mede articulação segmentar da coluna nem carga tecidual; requer vista lateral, confirmação profissional e não constitui diagnóstico.";
export function runPilatesSpineStretchForwardProtocol(frames:readonly PoseFrame[],options:PilatesSpineStretchForwardOptions={},now=new Date()):EngineResult{
 const side=options.side??"left",i=side==="left"?{ear:7,shoulder:11,hip:23,knee:25,ankle:27}:{ear:8,shoulder:12,hip:24,knee:26,ankle:28},quality=assessQuality(frames,{requiredLandmarkIndexes:Object.values(i),minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:10});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=first.landmarks[i.shoulder]!,h0=first.landmarks[i.hip]!,torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const baselineAngle=Math.atan2(Math.abs(s0.x-h0.x),Math.abs(s0.y-h0.y))*180/Math.PI;
 const samples=frames.flatMap(frame=>{const ear=frame.landmarks[i.ear],shoulder=frame.landmarks[i.shoulder],hip=frame.landmarks[i.hip],knee=frame.landmarks[i.knee],ankle=frame.landmarks[i.ankle];if(!ear||!shoulder||!hip||!knee||!ankle)return[];const kneeAngle=angleDegrees(hip,knee,ankle),headAngle=angleDegrees(ear,shoulder,hip);if(kneeAngle===null||headAngle===null)return[];const angle=Math.atan2(Math.abs(shoulder.x-hip.x),Math.abs(shoulder.y-hip.y))*180/Math.PI;return[{timestampMs:frame.timestampMs,flexion:Math.max(0,angle-baselineAngle),shoulderForward:Math.abs(shoulder.x-s0.x)/torso,kneeAngle,headTrunkAngle:headAngle}]});
 const minimum=options.minimumFlexionDegrees??18,tolerance=options.returnToleranceDegrees??6,minDuration=options.minimumRepetitionDurationMs??600,reps:Array<{start:number;end:number}>=[];let start=-1;samples.forEach((sample,index)=>{if(start<0&&sample.flexion>=minimum)start=index;if(start>=0&&sample.flexion<=tolerance){if(sample.timestampMs-samples[start]!.timestampMs>=minDuration)reps.push({start,end:index});start=-1}});
 if(!reps.length){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Nenhum ciclo completo de flexão e retorno foi detectado.",details:{maximumFlexionDegrees:Math.max(...samples.map(s=>s.flexion)),minimumFlexionDegrees:minimum}});return result([],quality,0,now)}
 const confidence=aggregateConfidence(quality,samples.length/frames.length),durations=reps.map(rep=>(samples[rep.end]!.timestampMs-samples[rep.start]!.timestampMs)/1000),range=(key:"flexion"|"kneeAngle"|"headTrunkAngle")=>Math.max(...samples.map(s=>s[key]))-Math.min(...samples.map(s=>s[key]));
 return result([metric("repetition_count",reps.length,"count",confidence),metric("spine_stretch_flexion_peak",Math.max(...samples.map(s=>s.flexion)),"deg",confidence),metric("spine_stretch_flexion_range",range("flexion"),"deg",confidence),metric("spine_stretch_shoulder_forward_max",Math.max(...samples.map(s=>s.shoulderForward)),"torso_ratio",confidence),metric("spine_stretch_knee_angle_range",range("kneeAngle"),"deg",confidence),metric("spine_stretch_head_trunk_angle_range",range("headTrunkAngle"),"deg",confidence),metric("repetition_time",mean(durations),"s",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-spine-stretch-forward",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
