import{aggregateConfidence}from"../confidence.js";import{angleDegrees,midpoint}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";
export interface PilatesHundredOptions{minimumArmPumpRange?:number;minimumPumpCount?:number}
const DISCLAIMER="Estimativa 2D do Pilates The Hundred para pesquisa e apoio à decisão. Não mede controle respiratório, requer confirmação profissional e não constitui diagnóstico.";
export function runPilatesHundredProtocol(frames:readonly PoseFrame[],options:PilatesHundredOptions={},now=new Date()):EngineResult{
 const required=[7,8,11,12,15,16,23,24,25,26,27,28]as const,quality=assessQuality(frames,{requiredLandmarkIndexes:required,minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:20});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=midpoint(first.landmarks[11]!,first.landmarks[12]!),h0=midpoint(first.landmarks[23]!,first.landmarks[24]!),torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);
 if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const samples=frames.flatMap((frame)=>{const shoulder=midpoint(frame.landmarks[11]!,frame.landmarks[12]!),hip=midpoint(frame.landmarks[23]!,frame.landmarks[24]!),wrist=midpoint(frame.landmarks[15]!,frame.landmarks[16]!),ear=midpoint(frame.landmarks[7]!,frame.landmarks[8]!);const leftKnee=angleDegrees(frame.landmarks[23]!,frame.landmarks[25]!,frame.landmarks[27]!),rightKnee=angleDegrees(frame.landmarks[24]!,frame.landmarks[26]!,frame.landmarks[28]!),head=angleDegrees(ear,shoulder,hip);if(leftKnee===null||rightKnee===null||head===null)return[];return[{timestampMs:frame.timestampMs,armPosition:(wrist.y-shoulder.y)/torso,armAsymmetry:Math.abs(frame.landmarks[15]!.y-frame.landmarks[16]!.y)/torso,trunkDrift:Math.hypot((shoulder.x-hip.x)-(s0.x-h0.x),(shoulder.y-hip.y)-(s0.y-h0.y))/torso,leftKnee,rightKnee,headAngle:head}]});
 const positions=samples.map((sample)=>sample.armPosition),minimum=Math.min(...positions),maximum=Math.max(...positions),range=maximum-minimum,minRange=options.minimumArmPumpRange??.08;
 if(range<minRange){quality.accepted=false;quality.reasons.push({code:"insufficient_depth",message:"Amplitude dos braços insuficiente para caracterizar os bombeamentos.",details:{armPumpRange:range,minimumArmPumpRange:minRange}});return result([],quality,0,now)}
 const lower=minimum+range*.35,upper=minimum+range*.65;type State="low"|"high";let state:State|undefined,transitions=0;
 for(const value of positions){const next:State|undefined=value<=lower?"low":value>=upper?"high":undefined;if(next&&state&&next!==state)transitions+=1;if(next)state=next}
 const pumps=Math.floor(transitions/2),requiredPumps=options.minimumPumpCount??3;
 if(pumps<requiredPumps){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Número insuficiente de bombeamentos completos.",details:{pumpCount:pumps,minimumPumpCount:requiredPumps}});return result([],quality,0,now)}
 const duration=(samples.at(-1)!.timestampMs-samples[0]!.timestampMs)/1000,cadence=duration>0?pumps/duration*60:0,confidence=aggregateConfidence(quality,samples.length/frames.length);
 const spread=(key:"leftKnee"|"rightKnee"|"headAngle")=>Math.max(...samples.map((sample)=>sample[key]))-Math.min(...samples.map((sample)=>sample[key]));
 return result([metric("hundred_arm_pump_count",pumps,"count",confidence),metric("hundred_arm_pump_cadence",cadence,"pumps_per_min",confidence),metric("hundred_arm_pump_range",range,"torso_ratio",confidence),metric("hundred_arm_asymmetry_mean",mean(samples.map((sample)=>sample.armAsymmetry)),"torso_ratio",confidence),metric("hundred_trunk_drift_max",Math.max(...samples.map((sample)=>sample.trunkDrift)),"torso_ratio",confidence),metric("hundred_left_knee_angle_range",spread("leftKnee"),"deg",confidence),metric("hundred_right_knee_angle_range",spread("rightKnee"),"deg",confidence),metric("hundred_head_trunk_angle_range",spread("headAngle"),"deg",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-the-hundred",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
