import{aggregateConfidence}from"../confidence.js";import{angleDegrees,midpoint}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";
export interface PilatesSingleLegStretchOptions{minimumKneeAngleDifference?:number;minimumStableFrames?:number;minimumAlternations?:number}
type LegState="left_flexed"|"right_flexed"|"neutral";
const DISCLAIMER="Estimativa 2D do Pilates Single Leg Stretch para pesquisa e apoio à decisão. Requer confirmação profissional e não constitui diagnóstico.";
export function runPilatesSingleLegStretchProtocol(frames:readonly PoseFrame[],options:PilatesSingleLegStretchOptions={},now=new Date()):EngineResult{
 const required=[11,12,23,24,25,26,27,28]as const,quality=assessQuality(frames,{requiredLandmarkIndexes:required,minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:12});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,shoulder0=midpoint(first.landmarks[11]!,first.landmarks[12]!),hip0=midpoint(first.landmarks[23]!,first.landmarks[24]!),torso=Math.hypot(shoulder0.x-hip0.x,shoulder0.y-hip0.y);
 if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const difference=options.minimumKneeAngleDifference??30,stableFrames=options.minimumStableFrames??2;
 const samples=frames.flatMap((frame)=>{const left=angleDegrees(frame.landmarks[23]!,frame.landmarks[25]!,frame.landmarks[27]!),right=angleDegrees(frame.landmarks[24]!,frame.landmarks[26]!,frame.landmarks[28]!);if(left===null||right===null)return[];const shoulder=midpoint(frame.landmarks[11]!,frame.landmarks[12]!),hip=midpoint(frame.landmarks[23]!,frame.landmarks[24]!);const state:LegState=left+difference<right?"left_flexed":right+difference<left?"right_flexed":"neutral";return[{timestampMs:frame.timestampMs,leftAngle:left,rightAngle:right,state,trunkDrift:Math.hypot((shoulder.x-hip.x)-(shoulder0.x-hip0.x),(shoulder.y-hip.y)-(shoulder0.y-hip0.y))/torso}]});
 const states:Array<{state:Exclude<LegState,"neutral">;timestampMs:number}>=[];let candidate:LegState="neutral",run=0;
 for(const sample of samples){if(sample.state==="neutral"){candidate="neutral";run=0;continue}if(sample.state===candidate)run+=1;else{candidate=sample.state;run=1}if(run===stableFrames&&states.at(-1)?.state!==candidate)states.push({state:candidate,timestampMs:sample.timestampMs})}
 const switches=states.slice(1).filter((state,index)=>state.state!==states[index]!.state),minimum=options.minimumAlternations??2;
 if(switches.length<minimum){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Alternância esquerda-direita insuficiente para caracterizar o Single Leg Stretch.",details:{alternations:switches.length,minimumAlternations:minimum}});return result([],quality,0,now)}
 const intervals=states.slice(1).map((state,index)=>(state.timestampMs-states[index]!.timestampMs)/1000),left=samples.map((sample)=>sample.leftAngle),right=samples.map((sample)=>sample.rightAngle),confidence=aggregateConfidence(quality,samples.length/frames.length);
 return result([metric("alternation_count",switches.length,"count",confidence),metric("single_leg_stretch_left_knee_range",Math.max(...left)-Math.min(...left),"deg",confidence),metric("single_leg_stretch_right_knee_range",Math.max(...right)-Math.min(...right),"deg",confidence),metric("single_leg_stretch_switch_time",mean(intervals),"s",confidence),metric("single_leg_stretch_trunk_drift_max",Math.max(...samples.map((sample)=>sample.trunkDrift)),"torso_ratio",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-single-leg-stretch",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
