import{aggregateConfidence}from"../confidence.js";import{midpoint}from"../kinematics.js";import{mean}from"../math.js";import{assessQuality}from"../quality.js";import type{EngineResult,MetricValue,PoseFrame}from"../types.js";
export interface PilatesSwimmingOptions{minimumContralateralDifference?:number;minimumStableFrames?:number;minimumAlternations?:number}
type SwimState="left_arm_right_leg"|"right_arm_left_leg"|"neutral";
const DISCLAIMER="Estimativa 2D do Pilates Swimming para pesquisa e apoio à decisão. Requer vista oblíqua ou posterior adequada, confirmação profissional e não constitui diagnóstico.";
export function runPilatesSwimmingProtocol(frames:readonly PoseFrame[],options:PilatesSwimmingOptions={},now=new Date()):EngineResult{
 const required=[11,12,15,16,23,24,27,28]as const,quality=assessQuality(frames,{requiredLandmarkIndexes:required,minimumVisibility:.5,minimumValidFrameRate:.7,minimumFrames:12});if(!quality.accepted)return result([],quality,0,now);
 const first=frames[0]!,s0=midpoint(first.landmarks[11]!,first.landmarks[12]!),h0=midpoint(first.landmarks[23]!,first.landmarks[24]!),torso=Math.hypot(s0.x-h0.x,s0.y-h0.y);
 if(!Number.isFinite(torso)||torso<=0){quality.accepted=false;quality.reasons.push({code:"invalid_frame",message:"Comprimento aparente do tronco inválido."});return result([],quality,0,now)}
 const baseline={lw:first.landmarks[15]!.y,rw:first.landmarks[16]!.y,la:first.landmarks[27]!.y,ra:first.landmarks[28]!.y},threshold=options.minimumContralateralDifference??.12;
 const samples=frames.map((frame)=>{const shoulder=midpoint(frame.landmarks[11]!,frame.landmarks[12]!),hip=midpoint(frame.landmarks[23]!,frame.landmarks[24]!);const leftArm=(baseline.lw-frame.landmarks[15]!.y)/torso,rightArm=(baseline.rw-frame.landmarks[16]!.y)/torso,leftLeg=(baseline.la-frame.landmarks[27]!.y)/torso,rightLeg=(baseline.ra-frame.landmarks[28]!.y)/torso;const a=leftArm+rightLeg,b=rightArm+leftLeg,difference=a-b;const state:SwimState=difference>=threshold?"left_arm_right_leg":difference<=-threshold?"right_arm_left_leg":"neutral";return{timestampMs:frame.timestampMs,leftArm,rightArm,leftLeg,rightLeg,state,contralateralImbalance:Math.abs(leftArm-rightLeg)+Math.abs(rightArm-leftLeg),trunkDrift:Math.hypot((shoulder.x-hip.x)-(s0.x-h0.x),(shoulder.y-hip.y)-(s0.y-h0.y))/torso}});
 const stable=options.minimumStableFrames??2,states:Array<{state:Exclude<SwimState,"neutral">;timestampMs:number}>=[];let candidate:SwimState="neutral",run=0;
 for(const sample of samples){if(sample.state==="neutral"){candidate="neutral";run=0;continue}if(sample.state===candidate)run+=1;else{candidate=sample.state;run=1}if(run===stable&&states.at(-1)?.state!==candidate)states.push({state:candidate,timestampMs:sample.timestampMs})}
 const switches=states.slice(1).filter((state,index)=>state.state!==states[index]!.state),minimum=options.minimumAlternations??2;
 if(switches.length<minimum){quality.accepted=false;quality.reasons.push({code:"incomplete_cycle",message:"Alternância contralateral insuficiente para caracterizar o Swimming.",details:{alternations:switches.length,minimumAlternations:minimum}});return result([],quality,0,now)}
 const intervals=states.slice(1).map((state,index)=>(state.timestampMs-states[index]!.timestampMs)/1000),duration=(states.at(-1)!.timestampMs-states[0]!.timestampMs)/1000,cadence=duration>0?switches.length/duration*60:0,confidence=aggregateConfidence(quality,samples.length/frames.length);
 const range=(key:"leftArm"|"rightArm"|"leftLeg"|"rightLeg")=>Math.max(...samples.map((sample)=>sample[key]))-Math.min(...samples.map((sample)=>sample[key]));
 return result([metric("swimming_alternation_count",switches.length,"count",confidence),metric("swimming_alternation_cadence",cadence,"alternations_per_min",confidence),metric("swimming_switch_time",mean(intervals),"s",confidence),metric("swimming_left_arm_range",range("leftArm"),"torso_ratio",confidence),metric("swimming_right_arm_range",range("rightArm"),"torso_ratio",confidence),metric("swimming_left_leg_range",range("leftLeg"),"torso_ratio",confidence),metric("swimming_right_leg_range",range("rightLeg"),"torso_ratio",confidence),metric("swimming_contralateral_imbalance_mean",mean(samples.map((sample)=>sample.contralateralImbalance)),"torso_ratio",confidence),metric("swimming_trunk_drift_max",Math.max(...samples.map((sample)=>sample.trunkDrift)),"torso_ratio",confidence)],quality,confidence,now)
}
function metric(id:string,value:number,unit:string,confidence:number):MetricValue{return{id,value:Number(value.toFixed(3)),unit,confidence}}function result(metrics:MetricValue[],quality:ReturnType<typeof assessQuality>,confidence:number,now:Date):EngineResult{return{schemaVersion:"fisiovision-engine-v0.1",protocolId:"pilates-swimming",protocolVersion:"0.1.0",status:quality.accepted?"accepted":"rejected",quality,metrics,confidence,reasons:quality.reasons,generatedAt:now.toISOString(),disclaimer:DISCLAIMER}}
