import type{PoseFrame}from"../types.js";
export interface SwimmingRecognitionCriterion{id:"prone_horizontal_posture"|"arms_projected"|"legs_lifted"|"contralateral_alternation";score:number;passed:boolean;evidence:Record<string,number>}
export interface SwimmingRecognitionResult{exerciseId:"pilates-swimming";accepted:boolean;score:number;criteria:SwimmingRecognitionCriterion[];failedCriteria:string[];reason?:"exercise_pose_mismatch"}
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,ratio=(x:boolean[])=>x.length?x.filter(Boolean).length/x.length:0,clamp=(x:number)=>Math.max(0,Math.min(1,x)),range=(x:number[])=>Math.max(...x)-Math.min(...x);
const correlation=(a:number[],b:number[])=>{const ma=avg(a),mb=avg(b),n=a.reduce((s,x,i)=>s+(x-ma)*(b[i]!-mb),0),d=Math.sqrt(a.reduce((s,x)=>s+(x-ma)**2,0)*b.reduce((s,x)=>s+(x-mb)**2,0));return d?n/d:0};
export function recognizePilatesSwimming(frames:readonly PoseFrame[]):SwimmingRecognitionResult{
 const groups=[[11,12],[15,16],[23,24],[27,28]]as const,visible=(f:PoseFrame,p:readonly[number,number])=>Math.max(f.landmarks[p[0]]?.visibility??0,f.landmarks[p[1]]?.visibility??0)>=.3,valid=frames.filter(f=>groups.every(p=>visible(f,p)));if(valid.length<20)return finish([]);
 const g=valid.map(f=>{const sh={x:(f.landmarks[11]!.x+f.landmarks[12]!.x)/2,y:(f.landmarks[11]!.y+f.landmarks[12]!.y)/2},hip={x:(f.landmarks[23]!.x+f.landmarks[24]!.x)/2,y:(f.landmarks[23]!.y+f.landmarks[24]!.y)/2},dx=sh.x-hip.x,dy=sh.y-hip.y,torso=Math.max(1e-9,Math.hypot(dx,dy)),side=(q:number)=>((f.landmarks[q]!.x-hip.x)*dy-(f.landmarks[q]!.y-hip.y)*dx)/torso/torso,length=(q:number,o:{x:number;y:number})=>Math.hypot(f.landmarks[q]!.x-o.x,f.landmarks[q]!.y-o.y)/torso;return{horizontal:Math.abs(dx)/torso,wristDiff:side(15)-side(16),ankleDiff:side(27)-side(28),wristLift:Math.min(Math.abs(side(15)),Math.abs(side(16))),ankleLift:Math.min(Math.abs(side(27)),Math.abs(side(28))),armLength:Math.min(length(15,sh),length(16,sh))}});
 const horizontal=ratio(g.map(x=>x.horizontal>=.65)),armLength=avg(g.map(x=>x.armLength)),wristLift=avg(g.map(x=>x.wristLift)),ankleLift=avg(g.map(x=>x.ankleLift)),wr=g.map(x=>x.wristDiff),an=g.map(x=>x.ankleDiff),corr=correlation(wr,an),wristRange=range(wr),ankleRange=range(an),alternation=Math.min(clamp((-corr-.4)/.3),clamp(wristRange/.3),clamp(ankleRange/.3));
 const criteria:SwimmingRecognitionCriterion[]=[{id:"prone_horizontal_posture",score:horizontal,passed:false,evidence:{horizontalFrameRatio:horizontal}},{id:"arms_projected",score:clamp((armLength/.8+wristLift/.08)/2),passed:false,evidence:{armLengthTorsoRatio:armLength,wristLiftTorsoRatio:wristLift}},{id:"legs_lifted",score:clamp(ankleLift/.18),passed:false,evidence:{minimumAnkleLiftTorsoRatio:ankleLift}},{id:"contralateral_alternation",score:alternation,passed:false,evidence:{contralateralCorrelation:corr,wristDifferenceRange:wristRange,ankleDifferenceRange:ankleRange}}];criteria.forEach(c=>c.passed=c.score>=.65);return finish(criteria)
}
function finish(criteria:SwimmingRecognitionCriterion[]):SwimmingRecognitionResult{const failed=criteria.filter(c=>!c.passed).map(c=>c.id),score=criteria.length?criteria.reduce((a,c)=>a+c.score,0)/criteria.length:0,accepted=criteria.length===4&&!failed.length;return{exerciseId:"pilates-swimming",accepted,score:Number(score.toFixed(3)),criteria,failedCriteria:failed,...(accepted?{}:{reason:"exercise_pose_mismatch"as const})}}