import type{PoseFrame}from"../types.js";
export interface SingleLegStretchRecognitionCriterion{id:"supine_orientation"|"head_shoulders_lifted"|"hands_support_flexed_leg"|"both_legs_suspended";score:number;passed:boolean;evidence:Record<string,number>}
export interface SingleLegStretchRecognitionResult{exerciseId:"pilates-single-leg-stretch";accepted:boolean;score:number;criteria:SingleLegStretchRecognitionCriterion[];failedCriteria:string[];reason?:"exercise_pose_mismatch"}
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,ratio=(x:boolean[])=>x.length?x.filter(Boolean).length/x.length:0,clamp=(x:number)=>Math.max(0,Math.min(1,x)),d=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
export function recognizePilatesSingleLegStretch(frames:readonly PoseFrame[]):SingleLegStretchRecognitionResult{
 const groups=[[7,8],[11,12],[15,16],[23,24],[25,26],[27,28]]as const,visible=(f:PoseFrame,p:readonly[number,number])=>Math.max(f.landmarks[p[0]]?.visibility??0,f.landmarks[p[1]]?.visibility??0)>=.3,valid=frames.filter(f=>groups.every(p=>visible(f,p)));if(valid.length<12)return finish([]);
 const pair=(f:PoseFrame,a:number,b:number)=>{const x=f.landmarks[a]!,y=f.landmarks[b]!,vx=x.visibility??0,vy=y.visibility??0,n=vx+vy;return n?{x:(x.x*vx+y.x*vy)/n,y:(x.y*vx+y.y*vy)/n}:{x:(x.x+y.x)/2,y:(x.y+y.y)/2}};
 const g=valid.map(f=>{const ear=pair(f,7,8),sh=pair(f,11,12),hip=pair(f,23,24),dx=sh.x-hip.x,dy=sh.y-hip.y,torso=Math.max(1e-9,Math.hypot(dx,dy)),perp=(p:{x:number;y:number})=>Math.abs((p.x-hip.x)*dy-(p.y-hip.y)*dx)/torso/torso,handKnee=Math.min(d(f.landmarks[15]!,f.landmarks[25]!),d(f.landmarks[15]!,f.landmarks[26]!),d(f.landmarks[16]!,f.landmarks[25]!),d(f.landmarks[16]!,f.landmarks[26]!))/torso;return{horizontal:Math.abs(dx)/torso,head:Math.abs((ear.x-sh.x)*dy-(ear.y-sh.y)*dx)/torso/torso,handKnee,bothLegs:Math.min(perp(f.landmarks[27]!),perp(f.landmarks[28]!))}});
 const horizontal=ratio(g.map(x=>x.horizontal>=.65)),head=avg(g.map(x=>x.head)),hand=avg(g.map(x=>x.handKnee)),legs=avg(g.map(x=>x.bothLegs));
 const criteria:SingleLegStretchRecognitionCriterion[]=[{id:"supine_orientation",score:horizontal,passed:false,evidence:{horizontalFrameRatio:horizontal}},{id:"head_shoulders_lifted",score:clamp(head/.08),passed:false,evidence:{headPerpendicularTorsoRatio:head}},{id:"hands_support_flexed_leg",score:clamp((.8-hand)/.6),passed:false,evidence:{handKneeDistanceTorsoRatio:hand}},{id:"both_legs_suspended",score:clamp(legs/.18),passed:false,evidence:{minimumAnkleHeightTorsoRatio:legs}}];criteria.forEach(c=>c.passed=c.score>=.65);return finish(criteria)
}
function finish(criteria:SingleLegStretchRecognitionCriterion[]):SingleLegStretchRecognitionResult{const failed=criteria.filter(c=>!c.passed).map(c=>c.id),score=criteria.length?criteria.reduce((a,c)=>a+c.score,0)/criteria.length:0,accepted=criteria.length===4&&!failed.length;return{exerciseId:"pilates-single-leg-stretch",accepted,score:Number(score.toFixed(3)),criteria,failedCriteria:failed,...(accepted?{}:{reason:"exercise_pose_mismatch"as const})}}