import type{PoseFrame}from"../types.js";
export interface TeaserRecognitionCriterion{id:"balanced_v_shape"|"trunk_raised"|"legs_raised"|"knees_extended"|"sustained_position";score:number;passed:boolean;evidence:Record<string,number>}
export interface TeaserRecognitionResult{exerciseId:"pilates-teaser";accepted:boolean;score:number;criteria:TeaserRecognitionCriterion[];failedCriteria:string[];reason?:"exercise_pose_mismatch"}
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,ratio=(x:boolean[])=>x.length?x.filter(Boolean).length/x.length:0,clamp=(x:number)=>Math.max(0,Math.min(1,x)),angle=(a:{x:number;y:number},b:{x:number;y:number},c:{x:number;y:number})=>{const ux=a.x-b.x,uy=a.y-b.y,vx=c.x-b.x,vy=c.y-b.y,d=Math.hypot(ux,uy)*Math.hypot(vx,vy);return d?Math.acos(Math.max(-1,Math.min(1,(ux*vx+uy*vy)/d)))*180/Math.PI:0};
export function recognizePilatesTeaser(frames:readonly PoseFrame[]):TeaserRecognitionResult{
 const groups=[[11,12],[23,24],[25,26],[27,28]]as const,visible=(f:PoseFrame,p:readonly[number,number])=>Math.max(f.landmarks[p[0]]?.visibility??0,f.landmarks[p[1]]?.visibility??0)>=.3,valid=frames.filter(f=>groups.every(p=>visible(f,p)));if(valid.length<20)return finish([]);
 const pair=(f:PoseFrame,a:number,b:number)=>{const x=f.landmarks[a]!,y=f.landmarks[b]!,vx=x.visibility??0,vy=y.visibility??0,n=vx+vy;return n?{x:(x.x*vx+y.x*vy)/n,y:(x.y*vx+y.y*vy)/n}:{x:(x.x+y.x)/2,y:(x.y+y.y)/2}};
 const g=valid.map(f=>{const sh=pair(f,11,12),hip=pair(f,23,24),ankle=pair(f,27,28),knee=(angle(f.landmarks[23]!,f.landmarks[25]!,f.landmarks[27]!)+angle(f.landmarks[24]!,f.landmarks[26]!,f.landmarks[28]!))/2,v=angle(sh,hip,ankle),trunk=sh.y<hip.y,legs=ankle.y<hip.y,characteristic=v>=55&&v<=120&&knee>=145&&trunk&&legs;return{v,knee,trunk,legs,characteristic}});
 const vRatio=ratio(g.map(x=>x.v>=55&&x.v<=120)),trunkRatio=ratio(g.map(x=>x.trunk)),legRatio=ratio(g.map(x=>x.legs)),extendedRatio=ratio(g.map(x=>x.knee>=145)),sustained=ratio(g.map(x=>x.characteristic)),vMean=avg(g.map(x=>x.v)),kneeMean=avg(g.map(x=>x.knee));
 const criteria:TeaserRecognitionCriterion[]=[{id:"balanced_v_shape",score:vRatio,passed:false,evidence:{vShapeFrameRatio:vRatio,meanVAngle:vMean}},{id:"trunk_raised",score:trunkRatio,passed:false,evidence:{shoulderAboveHipFrameRatio:trunkRatio}},{id:"legs_raised",score:legRatio,passed:false,evidence:{ankleAboveHipFrameRatio:legRatio}},{id:"knees_extended",score:extendedRatio,passed:false,evidence:{extendedKneeFrameRatio:extendedRatio,meanKneeAngle:kneeMean}},{id:"sustained_position",score:clamp(sustained/.7),passed:false,evidence:{characteristicFrameRatio:sustained}}];criteria.forEach(c=>c.passed=c.score>=.65);return finish(criteria)
}
function finish(criteria:TeaserRecognitionCriterion[]):TeaserRecognitionResult{const failed=criteria.filter(c=>!c.passed).map(c=>c.id),score=criteria.length?criteria.reduce((a,c)=>a+c.score,0)/criteria.length:0,accepted=criteria.length===5&&!failed.length;return{exerciseId:"pilates-teaser",accepted,score:Number(score.toFixed(3)),criteria,failedCriteria:failed,...(accepted?{}:{reason:"exercise_pose_mismatch"as const})}}