import type{PoseFrame}from"../types.js";
export interface SwanRecognitionCriterion{id:"prone_start"|"hands_support_near_shoulders"|"supported_trunk_extension"|"pelvis_legs_stable"|"complete_return";score:number;passed:boolean;evidence:Record<string,number>}
export interface SwanRecognitionResult{exerciseId:"pilates-swan";accepted:boolean;score:number;criteria:SwanRecognitionCriterion[];failedCriteria:string[];reason?:"exercise_pose_mismatch"}
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,clamp=(x:number)=>Math.max(0,Math.min(1,x)),range=(x:number[])=>Math.max(...x)-Math.min(...x),dist=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y);
const angle=(a:{x:number;y:number},b:{x:number;y:number},c:{x:number;y:number})=>{const ux=a.x-b.x,uy=a.y-b.y,vx=c.x-b.x,vy=c.y-b.y,d=Math.hypot(ux,uy)*Math.hypot(vx,vy);return d?Math.acos(Math.max(-1,Math.min(1,(ux*vx+uy*vy)/d)))*180/Math.PI:0};
export function recognizePilatesSwan(frames:readonly PoseFrame[]):SwanRecognitionResult{
 const groups=[[11,12],[13,14],[15,16],[23,24],[25,26],[27,28]]as const,visible=(f:PoseFrame,p:readonly[number,number])=>Math.max(f.landmarks[p[0]]?.visibility??0,f.landmarks[p[1]]?.visibility??0)>=.3,valid=frames.filter(f=>groups.every(p=>visible(f,p)));if(valid.length<30)return finish([]);
 const pair=(f:PoseFrame,a:number,b:number)=>{const x=f.landmarks[a]!,y=f.landmarks[b]!,vx=x.visibility??0,vy=y.visibility??0,n=vx+vy;return n?{x:(x.x*vx+y.x*vy)/n,y:(x.y*vx+y.y*vy)/n}:{x:(x.x+y.x)/2,y:(x.y+y.y)/2}};
 const first=valid.slice(0,Math.max(3,Math.floor(valid.length*.15))),startShoulder={x:avg(first.map(f=>pair(f,11,12).x)),y:avg(first.map(f=>pair(f,11,12).y))},startHip={x:avg(first.map(f=>pair(f,23,24).x)),y:avg(first.map(f=>pair(f,23,24).y))},torso=Math.max(1e-9,dist(startShoulder,startHip));
 const g=valid.map(f=>{const sh=pair(f,11,12),hip=pair(f,23,24),wrist=pair(f,15,16),ankle=pair(f,27,28),dx=sh.x-hip.x,dy=sh.y-hip.y;return{horizontal:Math.abs(dx)/Math.max(1e-9,Math.hypot(dx,dy)),shoulderY:sh.y,hipY:hip.y,wristX:wrist.x,wristY:wrist.y,handShoulder:dist(wrist,sh)/torso,ankleHip:dist(ankle,hip)/torso,elbow:(angle(f.landmarks[11]!,f.landmarks[13]!,f.landmarks[15]!)+angle(f.landmarks[12]!,f.landmarks[14]!,f.landmarks[16]!))/2}});
 const initialHorizontal=avg(g.slice(0,first.length).map(x=>x.horizontal)),initialHand=avg(g.slice(0,first.length).map(x=>x.handShoulder)),shoulders=g.map(x=>x.shoulderY),hips=g.map(x=>x.hipY),wristMovement=Math.hypot(range(g.map(x=>x.wristX)),range(g.map(x=>x.wristY)))/torso,shoulderRange=range(shoulders)/torso,hipRange=range(hips)/torso,elbowRange=range(g.map(x=>x.elbow)),ankleRange=range(g.map(x=>x.ankleHip)),baseline=avg(shoulders.slice(0,first.length)),peak=Math.min(...shoulders),tail=avg(shoulders.slice(-first.length)),lift=(baseline-peak)/torso,returnError=Math.abs(tail-baseline)/torso;
 const criteria:SwanRecognitionCriterion[]=[{id:"prone_start",score:clamp((initialHorizontal-.5)/.3),passed:false,evidence:{initialHorizontalRatio:initialHorizontal}},{id:"hands_support_near_shoulders",score:clamp((1-initialHand)/.5),passed:false,evidence:{initialHandShoulderDistanceTorsoRatio:initialHand}},{id:"supported_trunk_extension",score:Math.min(clamp(shoulderRange/.4),clamp(elbowRange/45),clamp((.8-wristMovement)/.5)),passed:false,evidence:{shoulderLiftRangeTorsoRatio:shoulderRange,elbowAngleRange:elbowRange,wristMovementTorsoRatio:wristMovement}},{id:"pelvis_legs_stable",score:Math.min(clamp((.8-hipRange)/.5),clamp((1-ankleRange)/.6)),passed:false,evidence:{hipMovementTorsoRatio:hipRange,ankleHipLengthRange:ankleRange}},{id:"complete_return",score:Math.min(clamp(lift/.25),clamp((.2-returnError)/.15)),passed:false,evidence:{liftTorsoRatio:lift,returnErrorTorsoRatio:returnError}}];criteria.forEach(c=>c.passed=c.score>=.65);return finish(criteria)
}
function finish(criteria:SwanRecognitionCriterion[]):SwanRecognitionResult{const failed=criteria.filter(c=>!c.passed).map(c=>c.id),score=criteria.length?criteria.reduce((a,c)=>a+c.score,0)/criteria.length:0,accepted=criteria.length===5&&!failed.length;return{exerciseId:"pilates-swan",accepted,score:Number(score.toFixed(3)),criteria,failedCriteria:failed,...(accepted?{}:{reason:"exercise_pose_mismatch"as const})}}