const video=document.querySelector("#video"),canvas=document.querySelector("#overlay"),ctx=canvas.getContext("2d");
const videoInput=document.querySelector("#videoInput"),landmarksInput=document.querySelector("#landmarksInput");
const status=document.querySelector("#status"),errors=document.querySelector("#errors"),empty=document.querySelector("#empty");
let artifact=null,videoUrl=null;
const connections=[[11,12],[11,23],[12,24],[23,24],[23,25],[24,26],[25,27],[26,28],[27,29],[28,30],[29,31],[30,32]];

videoInput.addEventListener("change",()=>{const file=videoInput.files[0];if(!file)return;if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=URL.createObjectURL(file);video.src=videoUrl;empty.hidden=true;status.textContent=`Vídeo local: ${file.name}`;});
landmarksInput.addEventListener("change",async()=>{try{const file=landmarksInput.files[0];if(!file)return;artifact=JSON.parse(await file.text());if(artifact.schemaVersion!=="fisiovision-landmarks-v0.1"||!Array.isArray(artifact.frames))throw new Error("Artefato de landmarks incompatível");status.textContent=`${artifact.frames.length} frames carregados`;draw();}catch(error){errors.textContent=error.message;}});
video.addEventListener("timeupdate",draw);video.addEventListener("loadedmetadata",resize);window.addEventListener("resize",resize);
function resize(){canvas.width=video.clientWidth*devicePixelRatio;canvas.height=video.clientHeight*devicePixelRatio;draw();}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(!artifact?.frames.length)return;const target=video.currentTime*1000;const frame=artifact.frames.reduce((best,current)=>Math.abs((current.timestampMs??0)-target)<Math.abs((best.timestampMs??0)-target)?current:best);const points=frame.landmarks??frame.poseLandmarks;if(!points)return;ctx.strokeStyle="#4ee0a0";ctx.lineWidth=3*devicePixelRatio;ctx.fillStyle="#ecfff7";for(const [a,b] of connections){const p=points[a],q=points[b];if(!p||!q||(p.visibility??1)<.5||(q.visibility??1)<.5)continue;ctx.beginPath();ctx.moveTo(p.x*canvas.width,p.y*canvas.height);ctx.lineTo(q.x*canvas.width,q.y*canvas.height);ctx.stroke();}for(const p of points){if((p.visibility??1)<.5)continue;ctx.beginPath();ctx.arc(p.x*canvas.width,p.y*canvas.height,3.5*devicePixelRatio,0,Math.PI*2);ctx.fill();}}
document.querySelector("#approve").addEventListener("click",()=>{errors.textContent="";try{if(!artifact)throw new Error("Importe os landmarks antes de aprovar.");const sampleId=value("sampleId"),reviewerId=value("reviewerId"),expectedStatus=value("expectedStatus");if(!sampleId||!reviewerId)throw new Error("ID da amostra e revisor são obrigatórios.");const repetitions=Number(value("repetitions"));if(expectedStatus==="accepted"&&(!Number.isInteger(repetitions)||repetitions<0))throw new Error("Informe uma contagem válida.");const now=new Date().toISOString();const manifest={schemaVersion:"fisiovision-dataset-v0.1",id:"local-review",version:"0.1.0",title:"Revisão local",source:"local-authorized",license:"proprietary-consented",consentOrLegalBasis:"preencher-antes-da-validação",containsIdentifiableMedia:false,createdAt:now,samples:[{id:sampleId,landmarksFile:`landmarks/${sampleId}.json`,protocolId:value("protocol"),expectedStatus,...(expectedStatus==="accepted"?{expectedRepetitions:repetitions}:{}),split:value("split")}]};const bundle={schemaVersion:"fisiovision-validation-package-v0.1",generatedAt:now,review:{reviewerId,notes:value("notes"),decision:"approved",reviewedAt:now},manifest,artifacts:{[`landmarks/${sampleId}.json`]:artifact}};download(`fisiovision-${sampleId}.json`,JSON.stringify(bundle,null,2));status.textContent="Pacote gerado localmente";}catch(error){errors.textContent=error.message;}});
function value(id){return document.querySelector("#"+id).value.trim()}function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
window.addEventListener("beforeunload",()=>{if(videoUrl)URL.revokeObjectURL(videoUrl)});
