import{randomUUID}from"node:crypto";
export const VALIDATED_PILATES_EXERCISES=["pilates-the-hundred","pilates-single-leg-stretch","pilates-swimming","pilates-swan","pilates-teaser"]as const;
export type ValidatedPilatesExerciseId=typeof VALIDATED_PILATES_EXERCISES[number];
export type AnalysisStatus="queued"|"processing"|"completed"|"failed";
export interface CreateAnalysisRequest{exerciseId:ValidatedPilatesExerciseId;videoUrl:string;idempotencyKey:string;callbackUrl?:string;metadata?:Record<string,string>}
export interface AnalysisJob{id:string;consumerId:string;exerciseId:ValidatedPilatesExerciseId;status:AnalysisStatus;videoUrl:string;idempotencyKey:string;callbackUrl?:string;metadata:Record<string,string>;createdAt:string;updatedAt:string;result?:unknown;error?:{code:string;message:string}}
export interface AnalysisStore{findByIdempotency(consumerId:string,key:string):Promise<AnalysisJob|undefined>;get(consumerId:string,id:string):Promise<AnalysisJob|undefined>;save(job:AnalysisJob):Promise<void>}
export class InMemoryAnalysisStore implements AnalysisStore{private readonly jobs=new Map<string,AnalysisJob>();async findByIdempotency(consumerId:string,key:string){return[...this.jobs.values()].find(j=>j.consumerId===consumerId&&j.idempotencyKey===key)}async get(consumerId:string,id:string){const j=this.jobs.get(id);return j?.consumerId===consumerId?j:undefined}async save(job:AnalysisJob){this.jobs.set(job.id,structuredClone(job))}}
export class AnalysisService{constructor(private readonly store:AnalysisStore,private readonly now=()=>new Date()){}async create(consumerId:string,input:CreateAnalysisRequest):Promise<{job:AnalysisJob;created:boolean}>{validate(consumerId,input);const existing=await this.store.findByIdempotency(consumerId,input.idempotencyKey);if(existing)return{job:existing,created:false};const timestamp=this.now().toISOString(),job:AnalysisJob={id:randomUUID(),consumerId,exerciseId:input.exerciseId,status:"queued",videoUrl:input.videoUrl,idempotencyKey:input.idempotencyKey,...(input.callbackUrl?{callbackUrl:input.callbackUrl}:{}),metadata:input.metadata??{},createdAt:timestamp,updatedAt:timestamp};await this.store.save(job);return{job,created:true}}async get(consumerId:string,id:string){return this.store.get(consumerId,id)}}
function validate(consumerId:string,input:CreateAnalysisRequest){if(!consumerId.trim())throw new Error("consumerId is required");if(!VALIDATED_PILATES_EXERCISES.includes(input.exerciseId))throw new Error("exercise is not commercially validated");if(!input.idempotencyKey?.trim()||input.idempotencyKey.length>128)throw new Error("idempotencyKey must contain 1 to 128 characters");secureUrl(input.videoUrl,"videoUrl");if(input.callbackUrl)secureUrl(input.callbackUrl,"callbackUrl");if(Object.keys(input.metadata??{}).length>20)throw new Error("metadata supports at most 20 entries")}
function secureUrl(value:string,name:string){let u:URL;try{u=new URL(value)}catch{throw new Error(name+" must be a valid URL")}if(u.protocol!=="https:"||u.username||u.password)throw new Error(name+" must use HTTPS without embedded credentials")}
